remote_theme: Phlow/feeling-responsive 
header:
    image_fullwidth: "unsplash_brooklyn-bridge_header.jpg"
    caption: This is a caption for the header image with link
    caption_url: https://unsplash.com/
